export const ASSETS = [
  { symbol: "SPY", name: "S&P 500 ETF", group: "指数ETF", dataSymbol: "spy.us", basePrice: 545 },
  { symbol: "QQQ", name: "Nasdaq 100 ETF", group: "指数ETF", dataSymbol: "qqq.us", basePrice: 480 },
  { symbol: "DIA", name: "Dow Jones ETF", group: "指数ETF", dataSymbol: "dia.us", basePrice: 390 },
  { symbol: "IWM", name: "Russell 2000 ETF", group: "指数ETF", dataSymbol: "iwm.us", basePrice: 205 },
  { symbol: "VTI", name: "Total US Stock Market ETF", group: "指数ETF", dataSymbol: "vti.us", basePrice: 270 },
  { symbol: "RSP", name: "S&P 500 Equal Weight ETF", group: "指数ETF", dataSymbol: "rsp.us", basePrice: 165 },
  { symbol: "SMH", name: "Semiconductor ETF", group: "指数ETF", dataSymbol: "smh.us", basePrice: 260 },
  { symbol: "SOXX", name: "Semiconductor ETF", group: "指数ETF", dataSymbol: "soxx.us", basePrice: 230 },
  { symbol: "TLT", name: "20+ Year Treasury Bond ETF", group: "指数ETF", dataSymbol: "tlt.us", basePrice: 92 },
  { symbol: "HYG", name: "High Yield Bond ETF", group: "指数ETF", dataSymbol: "hyg.us", basePrice: 78 },
  { symbol: "VIXY", name: "Short VIX Futures ETF", group: "指数ETF", dataSymbol: "vixy.us", basePrice: 13 },
  { symbol: "EWJ", name: "Japan ETF", group: "指数ETF", dataSymbol: "ewj.us", basePrice: 72 },
  { symbol: "DXJ", name: "Hedged Japan Equity ETF", group: "指数ETF", dataSymbol: "dxj.us", basePrice: 110 },
  { symbol: "1321JP", name: "Nikkei 225 ETF", group: "指数ETF", dataSymbol: "1321.jp", basePrice: 42000 },
  { symbol: "1306JP", name: "TOPIX ETF", group: "指数ETF", dataSymbol: "1306.jp", basePrice: 2900 },

  { symbol: "NVDA", name: "NVIDIA", group: "米国株", dataSymbol: "nvda.us", basePrice: 125 },
  { symbol: "AAPL", name: "Apple", group: "米国株", dataSymbol: "aapl.us", basePrice: 210 },
  { symbol: "MSFT", name: "Microsoft", group: "米国株", dataSymbol: "msft.us", basePrice: 440 },
  { symbol: "AMZN", name: "Amazon", group: "米国株", dataSymbol: "amzn.us", basePrice: 185 },
  { symbol: "GOOGL", name: "Alphabet", group: "米国株", dataSymbol: "googl.us", basePrice: 175 },
  { symbol: "META", name: "Meta Platforms", group: "米国株", dataSymbol: "meta.us", basePrice: 500 },
  { symbol: "TSLA", name: "Tesla", group: "米国株", dataSymbol: "tsla.us", basePrice: 180 },
  { symbol: "AVGO", name: "Broadcom", group: "米国株", dataSymbol: "avgo.us", basePrice: 1500 },
  { symbol: "AMD", name: "Advanced Micro Devices", group: "米国株", dataSymbol: "amd.us", basePrice: 160 },
  { symbol: "TSM", name: "Taiwan Semiconductor", group: "米国株", dataSymbol: "tsm.us", basePrice: 170 },
  { symbol: "ASML", name: "ASML", group: "米国株", dataSymbol: "asml.us", basePrice: 950 },
  { symbol: "ORCL", name: "Oracle", group: "米国株", dataSymbol: "orcl.us", basePrice: 125 },
  { symbol: "PLTR", name: "Palantir", group: "米国株", dataSymbol: "pltr.us", basePrice: 25 },
  { symbol: "JPM", name: "JPMorgan Chase", group: "米国株", dataSymbol: "jpm.us", basePrice: 200 },
  { symbol: "BAC", name: "Bank of America", group: "米国株", dataSymbol: "bac.us", basePrice: 40 },
  { symbol: "XOM", name: "Exxon Mobil", group: "米国株", dataSymbol: "xom.us", basePrice: 115 },
  { symbol: "CVX", name: "Chevron", group: "米国株", dataSymbol: "cvx.us", basePrice: 155 },
  { symbol: "LLY", name: "Eli Lilly", group: "米国株", dataSymbol: "lly.us", basePrice: 900 },
  { symbol: "UNH", name: "UnitedHealth", group: "米国株", dataSymbol: "unh.us", basePrice: 520 },
  { symbol: "COST", name: "Costco", group: "米国株", dataSymbol: "cost.us", basePrice: 850 },

  { symbol: "7203JP", name: "Toyota Motor", group: "日本株", dataSymbol: "7203.jp", basePrice: 3300 },
  { symbol: "6758JP", name: "Sony Group", group: "日本株", dataSymbol: "6758.jp", basePrice: 13000 },
  { symbol: "8035JP", name: "Tokyo Electron", group: "日本株", dataSymbol: "8035.jp", basePrice: 35000 },
  { symbol: "6857JP", name: "Advantest", group: "日本株", dataSymbol: "6857.jp", basePrice: 6500 },
  { symbol: "6861JP", name: "Keyence", group: "日本株", dataSymbol: "6861.jp", basePrice: 70000 },
  { symbol: "9984JP", name: "SoftBank Group", group: "日本株", dataSymbol: "9984.jp", basePrice: 9500 },
  { symbol: "9983JP", name: "Fast Retailing", group: "日本株", dataSymbol: "9983.jp", basePrice: 41000 },
  { symbol: "7974JP", name: "Nintendo", group: "日本株", dataSymbol: "7974.jp", basePrice: 8500 },
  { symbol: "6501JP", name: "Hitachi", group: "日本株", dataSymbol: "6501.jp", basePrice: 3600 },
  { symbol: "7011JP", name: "Mitsubishi Heavy Industries", group: "日本株", dataSymbol: "7011.jp", basePrice: 1700 },
  { symbol: "8306JP", name: "Mitsubishi UFJ Financial", group: "日本株", dataSymbol: "8306.jp", basePrice: 1600 },
  { symbol: "8316JP", name: "Sumitomo Mitsui Financial", group: "日本株", dataSymbol: "8316.jp", basePrice: 10000 },
  { symbol: "6098JP", name: "Recruit Holdings", group: "日本株", dataSymbol: "6098.jp", basePrice: 8000 },
  { symbol: "9432JP", name: "Nippon Telegraph and Telephone", group: "日本株", dataSymbol: "9432.jp", basePrice: 155 },
  { symbol: "7267JP", name: "Honda Motor", group: "日本株", dataSymbol: "7267.jp", basePrice: 1700 },
  { symbol: "8058JP", name: "Mitsubishi Corporation", group: "日本株", dataSymbol: "8058.jp", basePrice: 3100 },
  { symbol: "8031JP", name: "Mitsui & Co.", group: "日本株", dataSymbol: "8031.jp", basePrice: 7500 },
  { symbol: "6146JP", name: "Disco", group: "日本株", dataSymbol: "6146.jp", basePrice: 60000 },
  { symbol: "6920JP", name: "Lasertec", group: "日本株", dataSymbol: "6920.jp", basePrice: 30000 },
  { symbol: "4063JP", name: "Shin-Etsu Chemical", group: "日本株", dataSymbol: "4063.jp", basePrice: 6200 },

  { symbol: "EURUSD", name: "Euro / US Dollar", group: "FX", dataSymbol: "eurusd", basePrice: 1.08 },
  { symbol: "USDJPY", name: "US Dollar / Japanese Yen", group: "FX", dataSymbol: "usdjpy", basePrice: 157 },
  { symbol: "GBPUSD", name: "British Pound / US Dollar", group: "FX", dataSymbol: "gbpusd", basePrice: 1.27 },
  { symbol: "AUDUSD", name: "Australian Dollar / US Dollar", group: "FX", dataSymbol: "audusd", basePrice: 0.66 },
  { symbol: "USDCAD", name: "US Dollar / Canadian Dollar", group: "FX", dataSymbol: "usdcad", basePrice: 1.37 },
  { symbol: "USDCHF", name: "US Dollar / Swiss Franc", group: "FX", dataSymbol: "usdchf", basePrice: 0.91 },
  { symbol: "EURJPY", name: "Euro / Japanese Yen", group: "FX", dataSymbol: "eurjpy", basePrice: 170 },
  { symbol: "EURGBP", name: "Euro / British Pound", group: "FX", dataSymbol: "eurgbp", basePrice: 0.85 },
  { symbol: "EURAUD", name: "Euro / Australian Dollar", group: "FX", dataSymbol: "euraud", basePrice: 1.64 },
  { symbol: "EURCAD", name: "Euro / Canadian Dollar", group: "FX", dataSymbol: "eurcad", basePrice: 1.48 },
  { symbol: "EURCHF", name: "Euro / Swiss Franc", group: "FX", dataSymbol: "eurchf", basePrice: 0.98 },
  { symbol: "GBPJPY", name: "British Pound / Japanese Yen", group: "FX", dataSymbol: "gbpjpy", basePrice: 200 },
  { symbol: "GBPAUD", name: "British Pound / Australian Dollar", group: "FX", dataSymbol: "gbpaud", basePrice: 1.92 },
  { symbol: "GBPCAD", name: "British Pound / Canadian Dollar", group: "FX", dataSymbol: "gbpcad", basePrice: 1.74 },
  { symbol: "GBPCHF", name: "British Pound / Swiss Franc", group: "FX", dataSymbol: "gbpchf", basePrice: 1.15 },
  { symbol: "AUDJPY", name: "Australian Dollar / Japanese Yen", group: "FX", dataSymbol: "audjpy", basePrice: 104 },
  { symbol: "AUDCAD", name: "Australian Dollar / Canadian Dollar", group: "FX", dataSymbol: "audcad", basePrice: 0.91 },
  { symbol: "AUDCHF", name: "Australian Dollar / Swiss Franc", group: "FX", dataSymbol: "audchf", basePrice: 0.60 },
  { symbol: "CADJPY", name: "Canadian Dollar / Japanese Yen", group: "FX", dataSymbol: "cadjpy", basePrice: 114 },
  { symbol: "CADCHF", name: "Canadian Dollar / Swiss Franc", group: "FX", dataSymbol: "cadchf", basePrice: 0.66 },
  { symbol: "CHFJPY", name: "Swiss Franc / Japanese Yen", group: "FX", dataSymbol: "chfjpy", basePrice: 173 },

  { symbol: "XAUUSD", name: "Gold / US Dollar", group: "貴金属", dataSymbol: "xauusd", basePrice: 2320 },
  { symbol: "XAGUSD", name: "Silver / US Dollar", group: "貴金属", dataSymbol: "xagusd", basePrice: 29 },
  { symbol: "XPTUSD", name: "Platinum / US Dollar", group: "貴金属", dataSymbol: "xptusd", basePrice: 980 },
  { symbol: "XPDUSD", name: "Palladium / US Dollar", group: "貴金属", dataSymbol: "xpdusd", basePrice: 930 },
  { symbol: "GLD", name: "Gold ETF", group: "貴金属ETF・鉱山株", dataSymbol: "gld.us", basePrice: 215 },
  { symbol: "SLV", name: "Silver ETF", group: "貴金属ETF・鉱山株", dataSymbol: "slv.us", basePrice: 27 },
  { symbol: "PPLT", name: "Platinum ETF", group: "貴金属ETF・鉱山株", dataSymbol: "pplt.us", basePrice: 90 },
  { symbol: "PALL", name: "Palladium ETF", group: "貴金属ETF・鉱山株", dataSymbol: "pall.us", basePrice: 90 },
  { symbol: "GDX", name: "Gold Miners ETF", group: "貴金属ETF・鉱山株", dataSymbol: "gdx.us", basePrice: 35 },
  { symbol: "GDXJ", name: "Junior Gold Miners ETF", group: "貴金属ETF・鉱山株", dataSymbol: "gdxj.us", basePrice: 45 },
  { symbol: "NEM", name: "Newmont", group: "貴金属ETF・鉱山株", dataSymbol: "nem.us", basePrice: 45 },
  { symbol: "GOLD", name: "Barrick Gold", group: "貴金属ETF・鉱山株", dataSymbol: "gold.us", basePrice: 17 },
  { symbol: "AEM", name: "Agnico Eagle Mines", group: "貴金属ETF・鉱山株", dataSymbol: "aem.us", basePrice: 70 },
  { symbol: "PAAS", name: "Pan American Silver", group: "貴金属ETF・鉱山株", dataSymbol: "paas.us", basePrice: 22 },
  { symbol: "WPM", name: "Wheaton Precious Metals", group: "貴金属ETF・鉱山株", dataSymbol: "wpm.us", basePrice: 60 }
];

export function findAsset(symbol) {
  return ASSETS.find((asset) => asset.symbol === String(symbol || "").trim().toUpperCase());
}
